name: Deploy Lambda Function

on:
  workflow_call:
    inputs:
      directory:
        description: 'Directory to deploy'
        required: true
        type: string
      name:
        description: 'Name of lambda function'
        required: true
        type: string

jobs:
  deploy:
    defaults:
      run:
        working-directory: ${{ inputs.directory }}/${{ inputs.name }}
    runs-on: ubuntu-latest
    environment: 
      name: prod
      url: https://k7y75vforu3p5uydbk2lzhnyuu0qiqkh.lambda-url.us-east-1.on.aws/

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install --prefer-binary --compile -r requirements.txt -t .
      - name: Remove tests, testing, and examples
        run: rm -rf **/test*/ **/*example*/

      - name: Zip code
        run: zip -r deployment.zip
      - name: Check size of unzipped code (should be less than 250MB) and zipped code
        run: du -sh * && du -sh deployment.zip *

      - name: Deploy to Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: grantrank-${{ inputs.name }}-${{ secrets.ENVIRONMENT_NAME }}
          zip_file: ${{ inputs.directory }}/${{ inputs.name }}/deployment.zip
