name: Deploy Contract

on:
  push:
    # branches: [ main ]
    # paths:
    #   - "contracts/**"
    #   - "scripts/**"
    #   - "test/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npx hardhat test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment: 
      name: prod
      url: https://sepolia.etherscan.io/address/${{ steps.deploy-to-prod.outputs.graph-address }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - name: Deploy contract
        id: deploy-to-prod
        run: npx hardhat run scripts/deploy.js --network sepolia | tail -1 >> $GITHUB_OUTPUT
        env:
          SEPOLIA_PRIVATE_KEY: ${{ secrets.SEPOLIA_PRIVATE_KEY }}
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}