name: Deploy to Lambda

on:
  merge:
    branches:
      - main
  # push:
    # branches:
    #   - main
    # paths:
    #   - "backend/lambda_function.py"
    #   - "backend/requirements.txt"

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    defaults:
      run:
        working-directory: backend
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Determine branch name or pull
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/"* ]]; then
            export DEPLOYMENT_NAME=${GITHUB_REF#refs/heads/}
          else
            if [[ "${GITHUB_REF}" == "refs/pull/"* ]]; then
              export DEPLOYMENT_NAME="pull-request"
            fi
          fi

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt -t .

      - name: Zip code
        run: zip -r deployment.zip *

      - name: Deploy to Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: grantrank-${{ env.DEPLOYMENT_NAME }}
          zip_file: backend/deployment.zip

      - name: Test Lambda gives 200 response
        run: curl -s https://$AWS_REGION.amazonaws.com/$AWS_ACCOUNT_ID/grantrank-${{ env.DEPLOYMENT_NAME }} | grep -q "200 OK"