name: Deploy to Lambda

on:
  push:
    # branches:
    #   - main
    paths:
      - "backend/**"
      - ".github/workflows/deploy-lambda-function.yml"
  
jobs:
  deploy-api:
    uses: ./.github/workflows/deploy-lambda-function.yml
    with:
      directory: backend
      name: api
    secrets: inherit
    